from PilhaLista import PilhaLista, notacaoPolonesa

p = PilhaLista(4)
p.push(1)
p.push("tipo de elemento")
p.push((5, 4, 3))
p.push(True)
p.push(False)
print(p)
print(p.top())
p.pop()
p.pop()
p.pop()
p.pop()
p.pop()
print(p.top())
print(p)

notacaoPolonesa("a+b")
notacaoPolonesa("a+b+c")
notacaoPolonesa("a*b+c")
notacaoPolonesa("a+b*c")
notacaoPolonesa("a*(b+c)")
notacaoPolonesa("a/(b*c)*d")
notacaoPolonesa("(a+b)*c")
notacaoPolonesa("a*(b+(c*(d+e)))")
notacaoPolonesa("{a*[b+c*(d-e)*{a-b}]}")
notacaoPolonesa("a+[b*c]")
